In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('customers.csv')

In [3]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Date_of_Birth,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent
0,CUST00000001,Akash Agarwal,male,48,46-55,1977-01-13,akashagarwal@gmail.com,+91-9625152011,Patiala,Punjab,122521,2024-01-28,Gold,5,40098.48
1,CUST00000002,Farhan Rahman,male,73,65+,1952-01-20,farhanrahman@gmail.com,+91-8593009465,Durgapur,West Bengal,226518,2023-08-25,Platinum,8,63676.24
2,CUST00000003,Suresh Kumar,male,31,26-35,1994-01-09,sureshkumar755@gmail.com,+91-7935884774,Gurugram,Haryana,520400,2023-08-30,Silver,0,0.00
3,CUST00000004,Aditya Pandey,male,41,36-45,1984-01-12,adityapandey@outlook.com,+91-9015046072,Kolkata,West Bengal,735356,2024-03-11,Platinum,5,288324.84
4,CUST00000005,Hina Khan,female,53,46-55,1972-01-15,hinakhan433@gmail.com,+91-8813094271,Noida,UP,985141,2024-04-19,Platinum,4,69265.75

In [5]:
df['Date_of_Birth']=pd.to_datetime(df['Date_of_Birth'])

In [6]:
df['year']=df['Date_of_Birth'].dt.year

In [7]:
df.drop(columns=['Date_of_Birth'], inplace=True)

In [11]:
df['fname']=df['Customer_Name'].str.split(' ').str[0]
df['lname']=df['Customer_Name'].str.split(' ').str[-1]

In [9]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent,year,fname,lname
0,CUST00000001,Akash Agarwal,male,48,46-55,akashagarwal@gmail.com,+91-9625152011,Patiala,Punjab,122521,2024-01-28,Gold,5,40098.48,1977,Akash,Agarwal
1,CUST00000002,Farhan Rahman,male,73,65+,farhanrahman@gmail.com,+91-8593009465,Durgapur,West Bengal,226518,2023-08-25,Platinum,8,63676.24,1952,Farhan,Rahman
2,CUST00000003,Suresh Kumar,male,31,26-35,sureshkumar755@gmail.com,+91-7935884774,Gurugram,Haryana,520400,2023-08-30,Silver,0,0.00,1994,Suresh,Kumar
3,CUST00000004,Aditya Pandey,male,41,36-45,adityapandey@outlook.com,+91-9015046072,Kolkata,West Bengal,735356,2024-03-11,Platinum,5,288324.84,1984,Aditya,Pandey
4,CUST00000005,Hina Khan,female,53,46-55,hinakhan433@gmail.com,+91-8813094271,Noida,UP,985141,2024-04-19,Platinum,4,69265.75,1972,Hina,Khan

In [10]:
df.tail()

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent,year,fname,lname
39995,CUST00039996,Swati Joshi,female,43,36-45,swatijoshi369@outlook.com,+91-7611106033,Mysore,Karnataka,544799,2023-06-26,Platinum,4,137030.99,1982,Swati,Joshi
39996,CUST00039997,Nikhil Patel,male,33,26-35,nikhilpatel@gmail.com,+91-9819454194,Mumbai,Maharashtra,113783,2023-10-03,Platinum,8,193564.72,1992,Nikhil,Patel
39997,CUST00039998,Akash Yadav,male,24,18-25,akashyadav85@yahoo.com,+91-9602738649,Ahmedabad,Gujarat,927070,2024-04-12,Platinum,6,191316.63,2001,Akash,Yadav
39998,CUST00039999,Salman Ansari,male,52,46-55,salmanansari844@yahoo.com,+91-9209459900,Mysore,Karnataka,313975,2023-10-15,Silver,2,6482.53,1973,Salman,Ansari
39999,CUST00040000,Ahmed Ahmed,male,34,26-35,ahmedahmed@outlook.com,+91-8093120059,Ahmedabad,Gujarat,551113,2023-08-19,Platinum,8,216922.80,1991,Ahmed,Ahmed

In [12]:
df.rename(columns={'year': 'birth_year'}, inplace=True)

In [13]:
df['reg_year']=df['Registration_Date'].str.split('-').str[0]

In [14]:
df['reg_year'].astype(int)

0        2024
1        2023
2        2023
3        2024
4        2024
         ...
39995    2023
39996    2023
39997    2024
39998    2023
39999    2023
Name: reg_year, Length: 40000, dtype: int64

In [15]:
df['Age_Group'] = df['Age_Group'].astype(str).str.replace(r'\+', '', regex=True)

In [17]:
df['min_age']=df['Age_Group'].str.split('-').str[0]
df['max_age']=df['Age_Group'].str.split('-').str[1]

In [18]:
df['max_age'].isnull()

0        False
1         True
2        False
3        False
4        False
         ...
39995    False
39996    False
39997    False
39998    False
39999    False
Name: max_age, Length: 40000, dtype: bool

In [19]:
df['max_age']=df['max_age'].fillna(100)

In [21]:
df[['max_age','min_age']].astype(int)

       max_age  min_age
0           55       46
1          100       65
2           35       26
3           45       36
4           55       46
...        ...      ...
39995       45       36
39996       35       26
39997       25       18
39998       55       46
39999       35       26

[40000 rows x 2 columns]

In [22]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent,birth_year,fname,lname,reg_year,min_age,max_age
0,CUST00000001,Akash Agarwal,male,48,46-55,akashagarwal@gmail.com,+91-9625152011,Patiala,Punjab,122521,2024-01-28,Gold,5,40098.48,1977,Akash,Agarwal,2024,46,55
1,CUST00000002,Farhan Rahman,male,73,65,farhanrahman@gmail.com,+91-8593009465,Durgapur,West Bengal,226518,2023-08-25,Platinum,8,63676.24,1952,Farhan,Rahman,2023,65,100
2,CUST00000003,Suresh Kumar,male,31,26-35,sureshkumar755@gmail.com,+91-7935884774,Gurugram,Haryana,520400,2023-08-30,Silver,0,0.00,1994,Suresh,Kumar,2023,26,35
3,CUST00000004,Aditya Pandey,male,41,36-45,adityapandey@outlook.com,+91-9015046072,Kolkata,West Bengal,735356,2024-03-11,Platinum,5,288324.84,1984,Aditya,Pandey,2024,36,45
4,CUST00000005,Hina Khan,female,53,46-55,hinakhan433@gmail.com,+91-8813094271,Noida,UP,985141,2024-04-19,Platinum,4,69265.75,1972,Hina,Khan,2024,46,55

In [23]:
df['Customer_Tier'].unique()

<ArrowStringArray>
['Gold', 'Platinum', 'Silver']
Length: 3, dtype: str

In [25]:
df['Customer_Tier']=df['Customer_Tier'].map({'Gold':1,'Silver':0,'Platinum':2})

In [26]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,Age_Group,Email,Phone,City,State,Pincode,Registration_Date,Customer_Tier,Total_Orders,Total_Spent,birth_year,fname,lname,reg_year,min_age,max_age
0,CUST00000001,Akash Agarwal,male,48,46-55,akashagarwal@gmail.com,+91-9625152011,Patiala,Punjab,122521,2024-01-28,1,5,40098.48,1977,Akash,Agarwal,2024,46,55
1,CUST00000002,Farhan Rahman,male,73,65,farhanrahman@gmail.com,+91-8593009465,Durgapur,West Bengal,226518,2023-08-25,2,8,63676.24,1952,Farhan,Rahman,2023,65,100
2,CUST00000003,Suresh Kumar,male,31,26-35,sureshkumar755@gmail.com,+91-7935884774,Gurugram,Haryana,520400,2023-08-30,0,0,0.00,1994,Suresh,Kumar,2023,26,35
3,CUST00000004,Aditya Pandey,male,41,36-45,adityapandey@outlook.com,+91-9015046072,Kolkata,West Bengal,735356,2024-03-11,2,5,288324.84,1984,Aditya,Pandey,2024,36,45
4,CUST00000005,Hina Khan,female,53,46-55,hinakhan433@gmail.com,+91-8813094271,Noida,UP,985141,2024-04-19,2,4,69265.75,1972,Hina,Khan,2024,46,55

In [29]:
df['phone'] = df['Phone'].str.replace(r'^\+91-', '', regex=True)