In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in D:\aiml\python\venv\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\aiml\python\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in D:\aiml\python\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 4.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/9.8 MB 3.4 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/9.8 MB 3.9 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.8 MB 4.3 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.8 MB 4.2 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.8 MB 4.7 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.8 MB 5.0 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.8 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 5.5 MB/s  0:00:01
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.3 tzdata-2026.3

In [3]:
import pandas as pd

In [5]:
data = [1,2,3,4,5,6]
seri=pd.Series(data)
print(seri)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [6]:
data1 = {'a' : 1, 'b': 2 , 'c' : 3}
serie=pd.Series(data1)
print(serie)

a    1
b    2
c    3
dtype: int64

In [7]:
data = [1,2,3,4]
ind=['a','b','c','d']
pd.Series(data,ind)

a    1
b    2
c    3
d    4
dtype: int64

In [8]:
## data frame
data = {
    'name': ['krish','john','jack'],
    'age' : [20,30,40],
    'city' : ['banglore' , 'dubai' , 'mumbai']
}
df = pd.DataFrame(data)
print(df)

    name  age      city
0  krish   20  banglore
1   john   30     dubai
2   jack   40    mumbai

In [11]:
data = [
    {'name': 'krish','age' : 20, 'city':'mumbai'},
    {'name': 'abc','age' : 22, 'city':'delhi'},
    {'name': 'xyz','age' : 25, 'city':'banglore'}
]
df = pd.DataFrame(data)
print(df)

    name  age      city
0  krish   20    mumbai
1    abc   22     delhi
2    xyz   25  banglore

In [14]:
df = pd.read_csv('xyz.csv')
df.head(5)

,CustomerId,FirstName,LastName,Email,JoinDate,TotalSpent,Status
0,1001,Liam,Conner,liam.c@example.com,2025-01-15,450.25,Active
1,1002,Olivia,Martinez,olivia.m@example.com,2025-02-18,89.99,Active
2,1003,Ethan,Brooks,ebrooks@example.com,2025-03-02,0.00,Inactive
3,1004,Sophia,Yang,sophia.y@example.com,2025-05-12,1250.50,Premium
4,1005,Jackson,Tate,jtate@example.com,2025-06-20,320.00,Active

In [15]:
df.tail(5)

,CustomerId,FirstName,LastName,Email,JoinDate,TotalSpent,Status
5,1006,Emma,Smith,emma.s@example.com,2025-07-11,75.50,Active
6,1007,Lucas,Davis,lucas.d@example.com,2025-08-30,2100.00,Premium
7,1008,Ava,Brown,ava.b@example.com,2025-09-05,0.00,Inactive
8,1009,Mia,Garcia,mia.g@example.com,2025-10-22,540.75,Active
9,1010,Oliver,Rodriguez,oliver.r@example.com,2025-11-14,980.00,Premium

In [19]:
df.loc[0]

CustomerId                  1001
FirstName                   Liam
LastName                  Conner
Email         liam.c@example.com
JoinDate              2025-01-15
TotalSpent                450.25
Status                    Active
Name: 0, dtype: object

In [22]:
df['FirstName']

0       Liam
1     Olivia
2      Ethan
3     Sophia
4    Jackson
5       Emma
6      Lucas
7        Ava
8        Mia
9     Oliver
Name: FirstName, dtype: str

In [ ]:
df.iat[0][2]

In [26]:
df['salary']=[1,2,3,4,5,6,7,8,9,10]

In [27]:
df.drop('salary',axis=1)

,CustomerId,FirstName,LastName,Email,JoinDate,TotalSpent,Status
0,1001,Liam,Conner,liam.c@example.com,2025-01-15,450.25,Active
1,1002,Olivia,Martinez,olivia.m@example.com,2025-02-18,89.99,Active
2,1003,Ethan,Brooks,ebrooks@example.com,2025-03-02,0.00,Inactive
3,1004,Sophia,Yang,sophia.y@example.com,2025-05-12,1250.50,Premium
4,1005,Jackson,Tate,jtate@example.com,2025-06-20,320.00,Active
5,1006,Emma,Smith,emma.s@example.com,2025-07-11,75.50,Active
6,1007,Lucas,Davis,lucas.d@example.com,2025-08-30,2100.00,Premium
7,1008,Ava,Brown,ava.b@example.com,2025-09-05,0.00,Inactive
8,1009,Mia,Garcia,mia.g@example.com,2025-10-22,540.75,Active
9,1010,Oliver,Rodriguez,oliver.r@example.com,2025-11-14,980.00,Premium

In [28]:
df

,CustomerId,FirstName,LastName,Email,JoinDate,TotalSpent,Status,salary
0,1001,Liam,Conner,liam.c@example.com,2025-01-15,450.25,Active,1
1,1002,Olivia,Martinez,olivia.m@example.com,2025-02-18,89.99,Active,2
2,1003,Ethan,Brooks,ebrooks@example.com,2025-03-02,0.00,Inactive,3
3,1004,Sophia,Yang,sophia.y@example.com,2025-05-12,1250.50,Premium,4
4,1005,Jackson,Tate,jtate@example.com,2025-06-20,320.00,Active,5
5,1006,Emma,Smith,emma.s@example.com,2025-07-11,75.50,Active,6
6,1007,Lucas,Davis,lucas.d@example.com,2025-08-30,2100.00,Premium,7
7,1008,Ava,Brown,ava.b@example.com,2025-09-05,0.00,Inactive,8
8,1009,Mia,Garcia,mia.g@example.com,2025-10-22,540.75,Active,9
9,1010,Oliver,Rodriguez,oliver.r@example.com,2025-11-14,980.00,Premium,10

In [29]:
df.drop('salary',axis=1,inplace=True)

In [30]:
df

,CustomerId,FirstName,LastName,Email,JoinDate,TotalSpent,Status
0,1001,Liam,Conner,liam.c@example.com,2025-01-15,450.25,Active
1,1002,Olivia,Martinez,olivia.m@example.com,2025-02-18,89.99,Active
2,1003,Ethan,Brooks,ebrooks@example.com,2025-03-02,0.00,Inactive
3,1004,Sophia,Yang,sophia.y@example.com,2025-05-12,1250.50,Premium
4,1005,Jackson,Tate,jtate@example.com,2025-06-20,320.00,Active
5,1006,Emma,Smith,emma.s@example.com,2025-07-11,75.50,Active
6,1007,Lucas,Davis,lucas.d@example.com,2025-08-30,2100.00,Premium
7,1008,Ava,Brown,ava.b@example.com,2025-09-05,0.00,Inactive
8,1009,Mia,Garcia,mia.g@example.com,2025-10-22,540.75,Active
9,1010,Oliver,Rodriguez,oliver.r@example.com,2025-11-14,980.00,Premium