In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('xyz.csv')

In [3]:
data.describe()

       CustomerId   TotalSpent
count    10.00000    10.000000
mean   1005.50000   580.699000
std       3.02765   680.961007
min    1001.00000     0.000000
25%    1003.25000    79.122500
50%    1005.50000   385.125000
75%    1007.75000   870.187500
max    1010.00000  2100.000000

In [4]:
data.isnull()

   CustomerId  FirstName  LastName  Email  JoinDate  TotalSpent  Status
0       False      False     False  False     False       False   False
1       False      False     False  False     False       False   False
2       False      False     False  False     False       False   False
3       False      False     False  False     False       False   False
4       False      False     False  False     False       False   False
5       False      False     False  False     False       False   False
6       False      False     False  False     False       False   False
7       False      False     False  False     False       False   False
8       False      False     False  False     False       False   False
9       False      False     False  False     False       False   False

In [6]:
data.isnull().any(axis=1)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [7]:
data.isnull().any()

CustomerId    False
FirstName     False
LastName      False
Email         False
JoinDate      False
TotalSpent    False
Status        False
dtype: bool

In [8]:
data.isnull().sum()

CustomerId    0
FirstName     0
LastName      0
Email         0
JoinDate      0
TotalSpent    0
Status        0
dtype: int64

In [9]:
data.fillna(0)

,CustomerId,FirstName,LastName,Email,JoinDate,TotalSpent,Status
0,1001,Liam,Conner,liam.c@example.com,2025-01-15,450.25,Active
1,1002,Olivia,Martinez,olivia.m@example.com,2025-02-18,89.99,Active
2,1003,Ethan,Brooks,ebrooks@example.com,2025-03-02,0.00,Inactive
3,1004,Sophia,Yang,sophia.y@example.com,2025-05-12,1250.50,Premium
4,1005,Jackson,Tate,jtate@example.com,2025-06-20,320.00,Active
5,1006,Emma,Smith,emma.s@example.com,2025-07-11,75.50,Active
6,1007,Lucas,Davis,lucas.d@example.com,2025-08-30,2100.00,Premium
7,1008,Ava,Brown,ava.b@example.com,2025-09-05,0.00,Inactive
8,1009,Mia,Garcia,mia.g@example.com,2025-10-22,540.75,Active
9,1010,Oliver,Rodriguez,oliver.r@example.com,2025-11-14,980.00,Premium

In [10]:
data['CustomerId_fillna']=data['CustomerId'].fillna(data['CustomerId'].mean())

In [11]:
data

,CustomerId,FirstName,LastName,Email,JoinDate,TotalSpent,Status,CustomerId_fillna
0,1001,Liam,Conner,liam.c@example.com,2025-01-15,450.25,Active,1001
1,1002,Olivia,Martinez,olivia.m@example.com,2025-02-18,89.99,Active,1002
2,1003,Ethan,Brooks,ebrooks@example.com,2025-03-02,0.00,Inactive,1003
3,1004,Sophia,Yang,sophia.y@example.com,2025-05-12,1250.50,Premium,1004
4,1005,Jackson,Tate,jtate@example.com,2025-06-20,320.00,Active,1005
5,1006,Emma,Smith,emma.s@example.com,2025-07-11,75.50,Active,1006
6,1007,Lucas,Davis,lucas.d@example.com,2025-08-30,2100.00,Premium,1007
7,1008,Ava,Brown,ava.b@example.com,2025-09-05,0.00,Inactive,1008
8,1009,Mia,Garcia,mia.g@example.com,2025-10-22,540.75,Active,1009
9,1010,Oliver,Rodriguez,oliver.r@example.com,2025-11-14,980.00,Premium,1010

In [12]:
data['value_new']=data['CustomerId'].astype(float)

In [13]:
data

,CustomerId,FirstName,LastName,Email,JoinDate,TotalSpent,Status,CustomerId_fillna,value_new
0,1001,Liam,Conner,liam.c@example.com,2025-01-15,450.25,Active,1001,1001.0
1,1002,Olivia,Martinez,olivia.m@example.com,2025-02-18,89.99,Active,1002,1002.0
2,1003,Ethan,Brooks,ebrooks@example.com,2025-03-02,0.00,Inactive,1003,1003.0
3,1004,Sophia,Yang,sophia.y@example.com,2025-05-12,1250.50,Premium,1004,1004.0
4,1005,Jackson,Tate,jtate@example.com,2025-06-20,320.00,Active,1005,1005.0
5,1006,Emma,Smith,emma.s@example.com,2025-07-11,75.50,Active,1006,1006.0
6,1007,Lucas,Davis,lucas.d@example.com,2025-08-30,2100.00,Premium,1007,1007.0
7,1008,Ava,Brown,ava.b@example.com,2025-09-05,0.00,Inactive,1008,1008.0
8,1009,Mia,Garcia,mia.g@example.com,2025-10-22,540.75,Active,1009,1009.0
9,1010,Oliver,Rodriguez,oliver.r@example.com,2025-11-14,980.00,Premium,1010,1010.0

In [14]:
data['new_val']=data['CustomerId'].apply(lambda X: X*2)

In [15]:
data

,CustomerId,FirstName,LastName,Email,JoinDate,TotalSpent,Status,CustomerId_fillna,value_new,new_val
0,1001,Liam,Conner,liam.c@example.com,2025-01-15,450.25,Active,1001,1001.0,2002
1,1002,Olivia,Martinez,olivia.m@example.com,2025-02-18,89.99,Active,1002,1002.0,2004
2,1003,Ethan,Brooks,ebrooks@example.com,2025-03-02,0.00,Inactive,1003,1003.0,2006
3,1004,Sophia,Yang,sophia.y@example.com,2025-05-12,1250.50,Premium,1004,1004.0,2008
4,1005,Jackson,Tate,jtate@example.com,2025-06-20,320.00,Active,1005,1005.0,2010
5,1006,Emma,Smith,emma.s@example.com,2025-07-11,75.50,Active,1006,1006.0,2012
6,1007,Lucas,Davis,lucas.d@example.com,2025-08-30,2100.00,Premium,1007,1007.0,2014
7,1008,Ava,Brown,ava.b@example.com,2025-09-05,0.00,Inactive,1008,1008.0,2016
8,1009,Mia,Garcia,mia.g@example.com,2025-10-22,540.75,Active,1009,1009.0,2018
9,1010,Oliver,Rodriguez,oliver.r@example.com,2025-11-14,980.00,Premium,1010,1010.0,2020

In [18]:
grpd_add=data.groupby('CustomerId')['value_new'].agg(['mean','sum','count'])

In [19]:
grpd_add

              mean     sum  count
CustomerId
1001        1001.0  1001.0      1
1002        1002.0  1002.0      1
1003        1003.0  1003.0      1
1004        1004.0  1004.0      1
1005        1005.0  1005.0      1
1006        1006.0  1006.0      1
1007        1007.0  1007.0      1
1008        1008.0  1008.0      1
1009        1009.0  1009.0      1
1010        1010.0  1010.0      1